@url = http://localhost:3333

    # "goToUrl":"https://finance.yahoo.com/chart/AAPL",
    # "windowType":"chart"
POST {{url}}/open
Content-Type: application/json

{
    "goToUrl":"https://finance.yahoo.com/news/tech-stocks-stumble-worst-start-211736815.html",
    "windowType":"detailArticle"
}
###

POST {{url}}/close

###
POST {{url}}/scroll
Content-Type: application/json

{
    "source":"yahoo finance"
}

###
POST {{url}}/zoom
Content-Type: application/json

{
    "type":"in"
}


###
POST {{url}}/changeChart
Content-Type: application/json

{
    "type":"1 month"
}

###
POST {{url}}/findingCompanies
Content-Type: application/json

{
    "keyword":"apple"
}
###

POST {{url}}/findingAnswers
Content-Type: application/json

{
    "question":"what is price to earning ratio"
}
###
