@port = 4050
@Host =  http://localhost

@route = api/v1/questions

POST {{Host}}:{{port}}/{{route}}
Content-Type: application/json

{
    "question":"what's force selling",
    "answer":"I will just only sell stock with any profit without following selling strategy"
}

###

GET {{Host}}:{{port}}/{{route}}

