@port = 4050
@Host =  http://localhost

@route = api/v1/users

@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmM5MDE3NTRmZjVhZTQ4OTc4ZGFiZSIsImlhdCI6MTY0NzExMjM2MiwiZXhwIjoxNjU0ODAxOTYyfQ.Z4-NSEQBLPkUUFYZ-PbcfDfx9e3d5v2DHXgqDRZXT3U
POST {{Host}}:{{port}}/{{route}}
Content-Type: application/json

{
    "name":"nur",
    "password":"12341234",
    "email":"ssr4@yahoo.com",
    "gander":"Male"
}

###

POST {{Host}}:{{port}}/{{route}}/signup
Content-Type: application/json

{
    "name":"nur",
    "email":"mdnsdur1208@163.com",
    "password":"12341234",
    "gender":"Male"
}

###

POST {{Host}}:{{port}}/{{route}}/login
Content-Type: application/json

{
    
    "email":"mdnur1208@163.com",
    "password":"12341234"
    
}

###


POST {{Host}}:{{port}}/{{route}}/forgetPassword
Content-Type: application/json

{
    
    "email":"mdnur1208@163.com"
    
}


###


PUT {{Host}}:{{port}}/{{route}}/resetPassword
Content-Type: application/json

{
    
    "token":"470c86d98f31e2648f50cab29cacc5660595f66cf50909f606b49a9ac9ff090c",
    "password":"12345678"
    
}

### 

PUT {{Host}}:{{port}}/{{route}}/622c901754ff5ae48978dabe
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    
    "name":"ben",
    "gender":"female"
}
